# This workflow will run index.js (and commit the data generated to the repo)

name: Scrape

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: scrape
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: node index.js
