# This workflow will run index.js (and commit the data generated to the repo)

name: Scrape

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
  
jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: scrape
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: node index.js
    - name: add & commit
      uses: EndBug/add-and-commit@v9.0.1
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'data'

        # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
        # Default: '.'
        #cwd: '/home/runner/work/guttmacher-scrape/guttmacher-scrape'

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Updated data'

        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
        pathspec_error_handling: ignore
